[package]
name = "prolog"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"

[dependencies.crossterm]
version = "0.29"
features = ["event-stream"]
